"""Governed research lab; candidates never self-promote."""

from .boundaries import CandidateBoundaryError, validate_candidate_target
from .experiments import ExperimentLedger
from .outcomes import OutcomeIntegrityError, OutcomeLedger, build_postmortem
from .promotion import authorize_promotion
from .receipt_series import (
    ReceiptComparisonRow,
    ReceiptComparisonSpec,
    ReceiptReturnObservation,
    ReceiptSeriesError,
    derive_receipt_comparison_from_ledger,
    derive_receipt_observations,
    derive_receipt_observations_from_ledger,
    receipt_series_hash,
)
from .science import (
    V6_ROLE_TOOL_GRANTS,
    ExperimentPlan,
    ExperimentRun,
    ExperimentRunAbstention,
    Hypothesis,
    HypothesisFamily,
    NegativeResult,
    NoveltyReport,
    ReplicationRun,
    ResearchArchive,
    ResearchArtifactReceiptReference,
    ResearchBudget,
    ResearchClaim,
    ResearchContribution,
    ResearchContributionReport,
    ResearchCritiqueReceipt,
    ResearchEvidenceBinding,
    ResearchPostmortem,
    ResearchProgramme,
    ResearchTeam,
    ResearchTree,
    ResearchTreeNode,
    VerificationPackage,
    authorize_v6_research_tool,
    load_experiment_run,
    record_experiment_run,
)
from .strategy_evaluation import (
    ReceiptComparisonEvaluation,
    ReceiptComparisonValidationEvidence,
    StrategyEvaluationError,
    StrategyReturnSeries,
    common_sample_hash,
    evaluate_predeclared_strategies,
    evaluate_receipt_comparison,
    strategy_series_from_receipts,
    strategy_series_hash,
)
from .validation import (
    combinatorial_purged_splits,
    interval_combinatorial_purged_splits,
    interval_purged_walk_forward,
    purged_walk_forward,
    validation_statistics,
)

__all__ = [
    "V6_ROLE_TOOL_GRANTS",
    "CandidateBoundaryError",
    "ExperimentLedger",
    "ExperimentPlan",
    "ExperimentRun",
    "ExperimentRunAbstention",
    "Hypothesis",
    "HypothesisFamily",
    "NegativeResult",
    "NoveltyReport",
    "OutcomeIntegrityError",
    "OutcomeLedger",
    "ReceiptComparisonEvaluation",
    "ReceiptComparisonRow",
    "ReceiptComparisonSpec",
    "ReceiptComparisonValidationEvidence",
    "ReceiptReturnObservation",
    "ReceiptSeriesError",
    "ReplicationRun",
    "ResearchArchive",
    "ResearchArtifactReceiptReference",
    "ResearchBudget",
    "ResearchClaim",
    "ResearchContribution",
    "ResearchContributionReport",
    "ResearchCritiqueReceipt",
    "ResearchEvidenceBinding",
    "ResearchPostmortem",
    "ResearchProgramme",
    "ResearchTeam",
    "ResearchTree",
    "ResearchTreeNode",
    "StrategyEvaluationError",
    "StrategyReturnSeries",
    "VerificationPackage",
    "authorize_promotion",
    "authorize_v6_research_tool",
    "build_postmortem",
    "combinatorial_purged_splits",
    "common_sample_hash",
    "derive_receipt_comparison_from_ledger",
    "derive_receipt_observations",
    "derive_receipt_observations_from_ledger",
    "evaluate_predeclared_strategies",
    "evaluate_receipt_comparison",
    "interval_combinatorial_purged_splits",
    "interval_purged_walk_forward",
    "load_experiment_run",
    "purged_walk_forward",
    "receipt_series_hash",
    "record_experiment_run",
    "strategy_series_from_receipts",
    "strategy_series_hash",
    "validate_candidate_target",
    "validation_statistics",
]
